# Initial Preparation

In [27]:
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)

# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# TensorFlow ≥2.4 is required in this notebook
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.4"

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
sns.set()
np.random.seed(42)
tf.random.set_seed(42)

# For changes
USER = "ageent"
REPO = "y-mlOnPhrases"
SKIP_FLAG = "m3"    # Maybe "m1", "m2", ... or "all"

X_FILE = "X.npy"
Y1_FILE = "Y1.npy"
Y2_FILE = "Y2.npy"

In [2]:
# to save data or images
if "google.colab" in sys.modules:
    from google.colab import drive
    ROOT_GD = "/content/drive"
    STORAGE_PATH = ROOT_GD + "/My Drive/Colab Notebooks/" + REPO + "/"
    drive.mount(ROOT_GD)
else:   # local host
    STORAGE_PATH = "data/"

def save_data(prefix, file_name, data_frame):
    path = STORAGE_PATH + prefix + file_name
    data_frame.to_csv(path)

def save_pred(file_name, data_frame):
    save_data("predictions/", file_name, data_frame)
def save_trans_data(file_name, data_frame):
    save_data("transformed/", file_name, data_frame)

"""
fig, ax = plt.subplots()
ax.plot(data)
save_fig(fig, "fig_name")
"""
def save_fig(fig, fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = STORAGE_PATH + "img/" + fig_id + "." + fig_extension
    print("Saving figure", fig_id)
    if tight_layout:
        fig.tight_layout()
    fig.savefig(path, format=fig_extension, dpi=resolution)

In [3]:
# get the data
def get_github_data(path_to_file):
    """TODO: maybe need to use requests."""
    url = "https://raw.githubusercontent.com/{}/{}/{}"\
                            .format(USER, REPO, path_to_file)
    return np.load(url)

def get_localhost_data(file_name):
    path = "data/src/" + file_name
    return np.load(path)

if "google.colab" in sys.modules:
    PATH_TO_SRC = "main/data/src/"
    X_DATA = get_github_data(PATH_TO_SRC + X_FILE)
    Y1_DATA = get_github_data(PATH_TO_SRC + Y1_FILE)
    Y2_DATA = get_github_data(PATH_TO_SRC + Y2_FILE)
else:   # local host
    X_DATA = get_localhost_data(X_FILE)
    Y1_DATA = get_localhost_data(Y1_FILE)
    Y2_DATA = get_localhost_data(Y2_FILE)

In [4]:
print(X_DATA.shape)
print(X_DATA[0])

(800, 128)
[-0.98200285  5.3519163   0.6241017  -3.7863977  -2.0433748  -1.6433135
  5.0111694   0.11501709 -3.3202858   2.2631938   4.487829    3.1017983
  3.4887044  -4.942223    6.474518    0.77631605  5.3201113  -5.003155
 -6.0889516   3.9606059   4.9673815   0.5534823   2.3377123  -3.4211032
  5.278324    1.576092   -5.2838745   0.5925345  -1.2432728   1.5591371
 -1.0380139  -0.1521509   2.4624774   6.4752107  -4.399489   -2.6032155
  3.5712152   0.44489035  1.3303515   0.42398357  2.2737198   7.777598
 -3.3040464  -2.2658207  -7.7937617  -0.6868003   7.5321355   0.5417963
  2.423962    7.1077695  -0.6353128   3.4406264  -2.3372521   0.1237992
  1.9296596   4.452048    2.1478891  -2.770266   -9.235324   10.521325
 -8.574103   -3.127737   -5.1270823   5.001681   -2.710712    0.44150203
 -0.15498942  0.24662127 -0.21252623 -1.7166231  -1.0460446  -5.4344797
  2.56957    10.698443   -3.0771906   1.0651661  -0.32124305  5.725385
  7.167192    5.156452    5.6941953   6.4998055   6.7241

In [5]:
print(Y1_DATA.shape)
print(Y1_DATA[0:10])

(800,)
[1 2 2 0 1 0 2 2 1 0]


In [6]:
print(Y2_DATA.shape)
print(Y2_DATA[0:10])

(800,)
[ 6. 15. 34. 58. 27. 29. 50. 12.  7. 17.]


# Feature engineering
### Transforming

In [7]:
x = X_DATA.copy()
y2 = Y2_DATA.copy()

In [8]:
from sklearn.preprocessing import OneHotEncoder

transformer_y1 = OneHotEncoder()

In [9]:
y1 = transformer_y1.fit_transform(Y1_DATA[:, np.newaxis]).toarray()
y1

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

### Shuffle

In [10]:
t_ = np.hstack([x, y1, y2[:, np.newaxis]])
t_.shape

(800, 132)

In [11]:
np.random.shuffle(t_)
x = t_[:, :128].copy()
y1 = t_[:, 128:131].copy()
y2 = t_[:, 131].copy()
y = tf.concat([y1, y2[:, tf.newaxis]], axis=1)
%reset_selective -f t_

# Model selection
### Model 1
#### Loss and metrics

In [12]:
def classifier_metric(y_true, y_pred):
    return keras.metrics.categorical_accuracy(y_true[:, :3], y_pred)

def regressor_metric(y_true, y_pred):
    y_true_reg = tf.cast(y_true[:, 3], tf.float32)
    y_pred = tf.cast(y_pred, tf.float64)
    w_reg = 1 / 3
    y_pred_w = tf.cast(y_pred * w_reg, tf.float32)
    y_pred_reg = tf.reduce_sum(y_pred_w, axis=1)
    return tf.metrics.mean_squared_error(y_true_reg, y_pred_reg)

In [13]:
# test for metrics
y_true_ = tf.constant([[1, 0, 0, 60],
                       [0 ,1, 0, 50],
                       [0, 0, 1, 20],
                       [0, 1, 0, 4]])
y_pred_ = tf.constant([[99, 0, 0],
                       [0, 99, 0],
                       [0, 99, 9],
                       [0, 99, 0]])
print(classifier_metric(y_true_, y_pred_))
print(regressor_metric(y_true_, y_pred_))

tf.Tensor([1. 1. 0. 1.], shape=(4,), dtype=float32)
tf.Tensor(528.75, shape=(), dtype=float32)


In [14]:
def get_summands(y_true, y_pred):
    y_true_cl_ = tf.cast(y_true[:, :3], tf.float32)
    y_true_reg_ = tf.cast(y_true[:, 3], tf.float32)
    y_pred_ = tf.cast(y_pred, tf.float32)

    # classification
    y_pred_max = tf.reduce_max(y_pred_, axis=1)[:, tf.newaxis]
    y_pred_norm = y_pred_ / y_pred_max
    w_cl = 1.
    ss_cl = tf.square(y_true_cl_ - y_pred_norm) * w_cl

    # regression
    w_reg = 1 / 3
    y_pred_w = tf.cast(y_pred_ * w_reg, tf.float32)
    y_pred_reg = tf.reduce_sum(y_pred_w, axis=1)
    ss_reg = tf.square(y_true_reg_ - y_pred_reg)

    return tf.concat([ss_cl, ss_reg[:, tf.newaxis]], 1)

def loss1(y_true, y_pred):
    summands = get_summands(y_true, y_pred)
    return tf.reduce_sum(summands)

In [15]:
# test for loss1
y_true_ = tf.constant([[1, 0, 0, 60],
                       [0 ,1, 0, 50],
                       [2, 0, 1, 20],
                       [0, 1, 0, 4]])
y_pred_ = tf.constant([[99, 0, 0],
                       [0, 99, 0],
                       [1, 0, 99],
                       [0, 99, 0]])
loss1(y_true_, y_pred_)

<tf.Tensor: shape=(), dtype=float32, numpy=5996.476>

#### Create model

In [16]:
if SKIP_FLAG == "m1" or SKIP_FLAG == "all":
    model1 = keras.models.Sequential()
    model1.add(keras.layers.Dense(3, activation="linear", use_bias=False, input_shape=[128]))
    model1.compile(loss=loss1,
                   optimizer=tf.keras.optimizers.Adam(learning_rate=1e-1),
                   metrics=[classifier_metric, regressor_metric])
    history1 = model1.fit(x, y, epochs=30, validation_split=0.2)

### Model 2

In [17]:
def loss2(y_true, y_pred):
    summands = get_summands(y_true, y_pred)
    cl_mul = tf.reduce_sum(summands[:, :3], axis=1)
    reg_mul = summands[:, 3]
    return tf.reduce_sum(cl_mul * reg_mul)

In [18]:
# test for loss2
y_true_ = tf.constant([[1, 0, 0, 60],
                       [0 ,1, 0, 50],
                       [2, 0, 1, 20],
                       [0, 1, 0, 4]])
y_pred_ = tf.constant([[99, 0, 0],
                       [0, 99, 0],
                       [1, 0, 99],
                       [0, 99, 0]])
loss2(y_true_, y_pred_)

<tf.Tensor: shape=(), dtype=float32, numpy=703946.2>

In [19]:
if SKIP_FLAG == "m2" or SKIP_FLAG == "all":
    model2 = keras.models.Sequential()
    model2.add(keras.layers.Dense(3, activation="linear", use_bias=False, input_shape=[128]))
    model2.compile(loss=loss2,
                   optimizer=tf.keras.optimizers.Adam(learning_rate=1e-1),
                   metrics=[classifier_metric, regressor_metric])
    history2 = model2.fit(x, y, epochs=30, validation_split=0.2)

### Model 3

In [30]:
def loss3(y_true, y_pred):
    y_true_cl_ = tf.cast(y_true[:, :3], tf.float32)
    y_true_reg_ = tf.cast(y_true[:, 3], tf.float32)
    y_pred_ = tf.cast(y_pred, tf.float32)

    # classification
    y_pred_max = tf.reduce_max(y_pred_, axis=1)[:, tf.newaxis]
    y_pred_norm = y_pred_ / y_pred_max
    ss_cl = tf.square(y_true_cl_ - y_pred_norm)

    # regression
    w_reg = 1 / 3
    thr = tf.sqrt(2.)
    y_pred_w = tf.cast(y_pred_ * w_reg, tf.float32)
    y_pred_reg = tf.reduce_sum(y_pred_w, axis=1)
    delta_reg = y_true_reg_ - y_pred_reg
    is_more_threshold = delta_reg >= thr
    big_grad = tf.square(2. * delta_reg - thr)
    small_grad = tf.square((1/2) * delta_reg) + 1.5
    ss_reg = tf.where(is_more_threshold, big_grad, small_grad)
    summands = tf.concat([ss_cl, ss_reg[:, tf.newaxis]], 1)

    return tf.reduce_sum(summands)

In [24]:
# test for loss3
y_true_ = tf.constant([[1, 0, 0, 60],
                       [0 ,1, 0, 50],
                       [2, 0, 1, 20],
                       [0, 1, 0, 4]])
y_pred_ = tf.constant([[99, 0, 0],
                       [0, 99, 0],
                       [1, 0, 99],
                       [0, 99, 0]])
loss3(y_true_, y_pred_)

<tf.Tensor: shape=(), dtype=float32, numpy=3959.6982>

In [34]:
if SKIP_FLAG == "m3" or SKIP_FLAG == "all":
    model3 = keras.models.Sequential()
    model3.add(keras.layers.Dense(3, activation="linear", use_bias=False, input_shape=[128]))
    model3.compile(loss=loss3,
                   optimizer=tf.keras.optimizers.Adam(learning_rate=1e-2),
                   metrics=[classifier_metric, regressor_metric])
    history3 = model3.fit(x, y, epochs=30, validation_split=0.2)

Epoch 1/30
20/20 [==============================] - 5s 40ms/step - loss: 16977.3672 - classifier_metric: 0.3500 - regressor_metric: 802.8391 - val_loss: 10904.2881 - val_classifier_metric: 0.3250 - val_regressor_metric: 1350.3024
Epoch 2/30
20/20 [==============================] - 0s 12ms/step - loss: 4864.5024 - classifier_metric: 0.3609 - regressor_metric: 595.5914 - val_loss: 401.8012 - val_classifier_metric: 0.3500 - val_regressor_metric: 27.7470
Epoch 3/30
20/20 [==============================] - 0s 11ms/step - loss: 530.7423 - classifier_metric: 0.3641 - regressor_metric: 17.4510 - val_loss: 433.0273 - val_classifier_metric: 0.3562 - val_regressor_metric: 38.7186
Epoch 4/30
20/20 [==============================] - 0s 12ms/step - loss: 387.4963 - classifier_metric: 0.3703 - regressor_metric: 33.1127 - val_loss: 342.5783 - val_classifier_metric: 0.3562 - val_regressor_metric: 10.6860
Epoch 5/30
20/20 [==============================] - 0s 12ms/step - loss: 253.7389 - classifier_metr

In [38]:
history3 = model3.fit(x, y, epochs=100, validation_split=0.2)

Epoch 1/100
20/20 [==============================] - 0s 23ms/step - loss: 89.1174 - classifier_metric: 0.4469 - regressor_metric: 1.4572 - val_loss: 110.3733 - val_classifier_metric: 0.4187 - val_regressor_metric: 3.8434
Epoch 2/100
20/20 [==============================] - 0s 14ms/step - loss: 91.4183 - classifier_metric: 0.4484 - regressor_metric: 1.6549 - val_loss: 98.5834 - val_classifier_metric: 0.4187 - val_regressor_metric: 1.8922
Epoch 3/100
20/20 [==============================] - 0s 12ms/step - loss: 88.4166 - classifier_metric: 0.4500 - regressor_metric: 1.3909 - val_loss: 102.5534 - val_classifier_metric: 0.4187 - val_regressor_metric: 1.9235
Epoch 4/100
20/20 [==============================] - 0s 10ms/step - loss: 85.9537 - classifier_metric: 0.4500 - regressor_metric: 1.2807 - val_loss: 111.4879 - val_classifier_metric: 0.4187 - val_regressor_metric: 1.6640
Epoch 5/100
20/20 [==============================] - 0s 10ms/step - loss: 88.0604 - classifier_metric: 0.4531 - regre